import { TECH_TREE, isUpgradeNode, techNode, type TechKind } from "./tech";
import { TURRET_UPGRADES } from "./upgrades";
import { TOWER_KINDS, type TowerKind } from "./types";

/**
 * WHERE EVERY NODE SITS ON THE TECH TREE, and the one place that decides.
 *
 * THE BOARD IS A GRID AND THE GRID IS EDITABLE. Every node — turrets, the
 * utility chains, and every upgrade rung — owns one integer cell, and the
 * admin dashboard's Tech tree tab drags them around and writes the result
 * to public/tree.json. The game reads that over the authored cells at
 * startup, exactly the way balance.json overrides the tuning knobs.
 *
 * WHY IT IS A DOCUMENT AND NOT A TABLE IN THIS FILE. Laying out a skill
 * tree is not arithmetic, it is composition: which branch leaves which way,
 * how much air a wing needs, where the eye lands. Nobody gets that right by
 * writing coordinates and reloading — you get it right by dragging a node
 * and looking. So the authored cells below are a STARTING POINT, chosen to
 * be legible rather than final, and the real layout is whatever ends up in
 * the document.
 *
 * THE AUTHORED CELLS ARE STILL THE SOURCE OF TRUTH for anything the
 * document does not mention, and Reset in the editor returns to them. Once
 * a layout is settled it belongs here, in the same sense a settled price
 * belongs in tech.ts rather than in balance.json.
 *
 * THE CROSSING RULE IS NOT ENFORCED HERE and cannot be. An edge that
 * crosses another edge in open board turns the graph into a picture of
 * lines (see TechNodeDef.x) — the editor's job is to make that visible
 * while you drag, not this file's job to forbid it.
 */

/** one grid step, in board px. Nodes are smaller than a cell, so a cell is
 *  a position rather than a box: the air between them is what the layout is
 *  actually made of */
export const GRID = 110;

/**
 * HOW MANY GRID CELLS ONE AUTHORED TECH-TREE CELL IS WORTH.
 *
 * tech.ts lays the turrets out on its own coarse grid (TechNodeDef.x/y),
 * which is the design record of the WINGS — which subtree owns which strip
 * of board. That grid has no room between its cells for anything else, so
 * this one is three times finer in both axes: a turret still lands where
 * tech.ts put it, and there are now two free cells between any two turrets
 * for their upgrade branches to travel through.
 */
const SPREAD = 3;

/**
 * WHERE EACH TURRET'S UPGRADE BRANCH GOES, as cell offsets from the turret,
 * in rung order.
 *
 * These are the seed, not the design. They were generated by fanning each
 * branch out of its turret along a ray into whatever open board that
 * turret had beside it, and then snapped to the grid — which produces a
 * tree that reads correctly and no more than that. Move them.
 *
 * EVERY DOWNWARD BRANCH BELONGS TO A LEAF, and that is worth keeping
 * whatever else moves: a turret with children fans SIDEWAYS, so a parent's
 * edge down to its child never has a branch sitting in it. Ripple,
 * tsunami, parallax and fuse have no children, so they may drop straight
 * into the empty rows underneath them.
 */
const BRANCH: Record<TowerKind, readonly (readonly [number, number])[]> = {
  // the spine forks left and right below duo, so its own branch runs east
  duo: [[1, 0], [2, 0], [3, -1], [4, -2]],
  // the west wing: three turrets in a column, each branch one row clear of
  // the one above it
  scatter: [[-1, 0], [-2, 0], [-3, 1]],
  hail: [[-1, 0], [-2, 0], [-3, 0]],
  salvo: [[-1, 0], [-2, -1], [-3, -1]],
  fuse: [[0, 1], [-1, 2], [-2, 3]],
  ripple: [[0, 1], [-1, 2], [-1, 3]],
  swarmer: [[-1, 0], [-2, 0], [-3, 1]],
  cyclone: [[-1, 0], [-2, 0], [-3, 1]],
  spectre: [[-1, 0], [-2, 0], [-3, 0]],
  // the east wing, mirrored — and the branches that run off the right edge
  // simply make the board wider, which costs nothing
  arc: [[1, 0], [2, 0], [3, -1], [4, -1]],
  scorch: [[1, 0], [2, -1], [3, -1]],
  wave: [[-1, 0], [-2, 0], [-3, -1]],
  tsunami: [[0, 1], [0, 2], [-1, 3]],
  parallax: [[0, 1], [1, 2], [1, 3]],
  lancer: [[1, 0], [2, 0], [3, -1]],
  meltdown: [[1, 0], [2, 0], [3, -1]],
  foreshadow: [[1, 0], [2, 0], [3, 0]],
};

export interface Cell {
  x: number;
  y: number;
}

/** the authored cell of every node there is, built once */
const AUTHORED: Record<string, Cell> = {};
for (const n of TECH_TREE)
  if (!isUpgradeNode(n.id))
    AUTHORED[n.id] = { x: n.x * SPREAD, y: n.y * SPREAD };
for (const t of TOWER_KINDS) {
  const g = techNode(t);
  TURRET_UPGRADES[t].forEach((def, i) => {
    const [dx, dy] = BRANCH[t][i] ?? [i + 1, 0];
    AUTHORED[def.id] = { x: g.x * SPREAD + dx, y: g.y * SPREAD + dy };
  });
}

/**
 * A CATALOG THAT PUTS TWO NODES IN ONE CELL IS A PROGRAMMING ERROR, caught
 * the first time anything loads this module rather than by a player
 * wondering why the tree has a node missing. It is the same bargain
 * mutation.ts makes with its own list: the table is authored by hand, so
 * the table checks itself. A SAVED DOCUMENT is not held to this — see
 * applyLayoutOverrides for why.
 */
{
  const seen = new Map<string, string>();
  for (const [id, c] of Object.entries(AUTHORED)) {
    const key = `${c.x},${c.y}`;
    const other = seen.get(key);
    if (other) throw new Error(`"${id}" and "${other}" both sit at cell ${key}`);
    seen.set(key, id);
  }
}

const overrides = new Map<string, Cell>();

/** the cell in force for a node — the document's, or the authored one */
export const cellOf = (id: string): Cell =>
  overrides.get(id) ?? AUTHORED[id] ?? { x: 0, y: 0 };

/** where a Reset returns to */
export const authoredCell = (id: string): Cell => AUTHORED[id] ?? { x: 0, y: 0 };

/** has this node been dragged off its authored cell? */
export const isMoved = (id: string): boolean => overrides.has(id);

/** put a node somewhere; undefined returns it to the authored cell */
export function setCell(id: string, cell: Cell | undefined): void {
  if (!AUTHORED[id]) return;
  if (!cell) overrides.delete(id);
  else overrides.set(id, { x: Math.round(cell.x), y: Math.round(cell.y) });
}

/** only what has actually been moved, for the document */
export function allLayoutOverrides(): Record<string, Cell> {
  return Object.fromEntries([...overrides].map(([k, v]) => [k, { ...v }]));
}

/**
 * Replace every override at once — what a saved document applies.
 *
 * IT NEVER REJECTS A LAYOUT FOR BEING UGLY, and it does not check for two
 * nodes in one cell either. A half-finished layout is a normal thing to
 * have saved: the editor is used by dragging, looking, and dragging again,
 * and a loader that refused the middle of that would make the tool useless.
 * Nodes the build has never heard of are dropped, because those are the
 * only entries that could break anything.
 */
export function applyLayoutOverrides(doc: Record<string, unknown>): void {
  overrides.clear();
  for (const [id, v] of Object.entries(doc)) {
    if (!AUTHORED[id] || !v || typeof v !== "object") continue;
    const { x, y } = v as Partial<Cell>;
    if (typeof x !== "number" || typeof y !== "number") continue;
    if (!Number.isFinite(x) || !Number.isFinite(y)) continue;
    overrides.set(id, { x: Math.round(x), y: Math.round(y) });
  }
}

/** every node the board draws, in one list — what the editor iterates */
export const LAYOUT_IDS: readonly TechKind[] = Object.keys(AUTHORED) as TechKind[];

// ---------- the document ------------------------------------------------

/** where the layout lives, served straight out of public/ */
const DOC_URL = "/tree.json";

/**
 * Read the saved layout over the authored one.
 *
 * NEVER REJECTS, for the same reason loadBalanceDoc does not: this is
 * called from the game's startup Promise.all, and a missing or mangled
 * layout file must cost the player nothing worse than the shipped tree.
 */
export async function loadLayoutDoc(): Promise<void> {
  try {
    const res = await fetch(DOC_URL, { cache: "no-store" });
    if (!res.ok) return;
    const parsed = (await res.json()) as unknown;
    if (!parsed || typeof parsed !== "object") return;
    applyLayoutOverrides(parsed as Record<string, unknown>);
  } catch {
    // offline, or a half-written file mid-save: the authored cells stand
  }
}

/** Persist the layout now in force. Returns false rather than throwing so
 *  the editor can say "not saved" without losing the drag on screen. */
export async function saveLayoutDoc(
  doc: Record<string, Cell>,
): Promise<boolean> {
  try {
    const res = await fetch("/api/tree", {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify(doc),
    });
    return res.ok;
  } catch {
    return false;
  }
}
