/**
 * The service worker, written against a bundle that already exists — run
 * AFTER the export, over out/, because the precache list is the file list
 * and half of those names carry a build hash.
 *
 * WHY PRECACHE THE WHOLE BUNDLE. The point of the offline build is a game
 * that starts somewhere with no network at all, so "cache it when it is
 * first asked for" is the one strategy that cannot work: the sprite the
 * run needs is the one that was never asked for at home. Every byte is
 * taken at install and the run is served entirely out of the cache
 * afterwards, network or not.
 *
 * IT ALSO PUTS BACK THE SIM'S THREAD. Shared memory needs a cross-origin
 * isolated page (game/shared.ts), which needs COOP and COEP on the
 * document, which a static host does not send — so the worker adds them to
 * everything it serves. Without this the iPad quietly takes the
 * single-threaded fallback (game/workerhost.ts), which is exactly the
 * machine that can least afford it.
 */
import { createHash } from "node:crypto";
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";

const root = new URL("../out/", import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1");

const files = [];
(function walk(dir) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p);
    else files.push(p);
  }
})(root);

// what the browser will ask for: a root-relative URL a slash at a time
const urls = files
  .map((p) => "/" + relative(root, p).split(sep).join("/"))
  // index.html is fetched as "/" — the navigation, not the file name
  .map((u) => (u === "/index.html" ? "/" : u))
  // Next's RSC payloads are never requested by a static export at runtime
  .filter((u) => !u.endsWith(".txt"))
  .sort();

let bytes = 0;
for (const p of files) bytes += statSync(p).size;

// the cache name has to change whenever any byte does, or an install after
// a rebuild would adopt the old cache and serve the old game
const stamp = createHash("sha256")
  .update(files.map((p) => relative(root, p) + statSync(p).size).join("\n"))
  .digest("hex")
  .slice(0, 12);

const sw = `// generated by scripts/gen-sw.mjs — do not edit
const CACHE = "animechs-${stamp}";
const URLS = ${JSON.stringify(urls)};

// COOP/COEP on every response, which is what buys the sim its own thread
// (game/shared.ts). CORP too, or this page could not load its own sprites
// under require-corp.
const isolate = (res) => {
  const h = new Headers(res.headers);
  h.set("Cross-Origin-Opener-Policy", "same-origin");
  h.set("Cross-Origin-Embedder-Policy", "require-corp");
  h.set("Cross-Origin-Resource-Policy", "same-origin");
  return new Response(res.body, { status: res.status, statusText: res.statusText, headers: h });
};

// the download is the ONE thing the player has to watch before they leave
// the network, so it is reported rather than silent
// wrapped, because the precache is the critical path and telling anyone
// about it is not: a messaging failure must never fail the install
const say = async (msg) => {
  try {
    for (const c of await self.clients.matchAll({ includeUncontrolled: true, type: "window" }))
      c.postMessage(msg);
  } catch {}
};

self.addEventListener("install", (e) => {
  e.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE);
      // in batches, because a few thousand requests at once stalls Safari,
      // and one at a time so a single 404 cannot fail the whole install
      for (let i = 0; i < URLS.length; i += 40) {
        await Promise.all(
          URLS.slice(i, i + 40).map((u) =>
            cache.add(new Request(u, { cache: "reload" })).catch(() => {}),
          ),
        );
        await say({ type: "precache", done: Math.min(i + 40, URLS.length), total: URLS.length });
      }
      await self.skipWaiting();
    })(),
  );
});

// what a later launch asks to find out whether the bundle is really all
// here — a half-finished download must not look like a finished one
self.addEventListener("message", (e) => {
  if (e.data?.type !== "status") return;
  e.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE);
      const have = (await cache.keys()).length;
      e.source?.postMessage({ type: "status", cached: have, total: URLS.length });
    })(),
  );
});

self.addEventListener("activate", (e) => {
  e.waitUntil(
    (async () => {
      for (const k of await caches.keys()) if (k !== CACHE) await caches.delete(k);
      await self.clients.claim();
    })(),
  );
});

self.addEventListener("fetch", (e) => {
  const { request } = e;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  e.respondWith(
    (async () => {
      const cache = await caches.open(CACHE);
      // a navigation is the app shell whatever the path says: the export is
      // one page, and offline there is nothing else to serve
      const key = request.mode === "navigate" ? "/" : url.pathname;
      const hit = (await cache.match(key)) ?? (await cache.match(request));
      if (hit) return isolate(hit);
      try {
        const res = await fetch(request);
        if (res.ok && res.type === "basic") cache.put(url.pathname, res.clone());
        return isolate(res);
      } catch {
        const shell = await cache.match("/");
        if (shell && request.mode === "navigate") return isolate(shell);
        return new Response("", { status: 504, statusText: "offline" });
      }
    })(),
  );
});
`;

writeFileSync(join(root, "sw.js"), sw);
console.log(
  `sw.js  ${urls.length} files, ${(bytes / 1024 / 1024).toFixed(1)} MB precached, cache animechs-${stamp}`,
);
